import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * The published skill states the live authoring contract.
 *
 * WHY THIS EXISTS: `skill-package.test.ts` checks PACKAGING — frontmatter, directory naming, the
 * tarball file list — and has never verified a contract statement. Meanwhile three required
 * condition keys (`clock`, `closes` with contract 44, `exit` with 44) and the whole seven-key
 * `entry` axis (44 and 47) reached the boundary while these documents said nothing about them. An
 * author composing faithfully from the published recipes could not produce a CREATE the server
 * accepts, and nothing here could see it.
 *
 * WHAT IT READS NOW, AND WHY THAT CHANGED THE GATE'S JOB. This used to read
 * `skills/battlegrid-strategy-studio/`, a document authored in this repository — an old fork of the
 * server repository's `strategy-examples` skill. Two authored copies of one contract statement meant
 * two independently written checkers over one rule, which are free to disagree; the disagreement
 * surfaces as a document that passes its own gate while being wrong.
 *
 * `battlegrid-app` now owns the single authored copy and EXPORTS it here
 * (`skills/battlegrid-strategy-examples/`, generated by its
 * `server/scripts/export-mcp-skills.mjs` — see `skill-provenance.test.ts`). Its own
 * `authoring-recipe-contract.test.ts` gates the same bytes against the same digest, with the same
 * headings. So this is no longer a second opinion; it is the **arrival check on an exported pair**.
 * The document and the digest fixture travel from one commit, and this asserts they actually match
 * on arrival — the one failure the upstream gate cannot see, because upstream the two are never
 * apart. `skill-provenance.test.ts` proves the pair was not tampered with; this proves it is
 * internally consistent.
 *
 * HEADINGS ARE THE APP DOCUMENT'S OWN. Not a translation table maintained here — that would
 * reintroduce the second implementation this consolidation removed. The three studio-specific
 * targets went with the studio: its `recipes.md` `## Custom section shape` is the app document's
 * `## Report sections` (axis `customSection`), and its `## Entry discipline recipes` trigger
 * coverage is carried by `## Entry`, which this file already checks.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO — freshness. Do not add a check that the vendored digest's
 * `contractVersion` matches the latest contract the README documents. Both files live HERE and only
 * ever move together, and a contract move upstream needs nothing from this package — no pull
 * request, no release, therefore no CI run here. Such a check passes green in exactly the case it
 * would be written for: both artifacts frozen while the server advances. That is the same shape as
 * this package sitting at 11.0.0 against a deployed contract of 19.3.0 while nothing failed. The
 * freshness obligation lives in the server repository, which observes every contract move by
 * construction (`LAST_VENDORED_DIGEST_CONTRACT_VERSION`, asserted in `mcp-catalog.protocol.test.ts`)
 * — and, since the export lane exists, performs the re-vendoring rather than only detecting it.
 */

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

interface ContractDigest {
  readonly axes: Readonly<Record<string, readonly string[]>>;
  readonly domains: Readonly<Record<string, readonly string[]>>;
  readonly bounds: { readonly conditionMaxCloses: number; readonly entryMaxCloses: number };
  readonly metricKeys: readonly string[];
}

const digest: ContractDigest = JSON.parse(
  readFileSync(join(repoRoot, 'src', '__fixtures__', 'authoring-contract-digest.json'), 'utf8'),
) as ContractDigest;

/** The exported document that states the authoring contract. */
const skill = readFileSync(
  join(repoRoot, 'skills', 'battlegrid-strategy-examples', 'SKILL.md'),
  'utf8',
);

/** Where each documented axis states its contract, in the exported document. */
const AXIS_HEADING: Readonly<Record<string, string>> = {
  entry: '## Entry',
  condition: '## Conditions',
  customSection: '## Report sections',
  rule: '## Signal rules',
  gates: '## Routing gates',
  tradeLevels: '## Trade levels',
  positionManagement: '## Position management',
};

/** The section where a vocabulary-absence claim may live, in the one document that makes them. */
const ABSENCE_HEADING = '## Not expressible — the catalog keys this needs';

const ABSENCE_PHRASES = [
  'not expressible',
  'not in the catalog',
  'no direct equivalent',
  'catalog carries no',
  // Added after it slipped through: contract 49.1's `PDH`/`PDL` retraction corrected the summary
  // table, the RSI-2 section and the absence table, but section 8 still told authors "PDH/PDL as
  // exact levels are not addressable" — a metric-absence claim wearing a synonym this list did not
  // carry, written with unbackticked keys so the key check above could not see it either. Both
  // detectors were blind to the same sentence, and it shipped to npm. Kept when this gate moved to
  // the exported document: it is a strictly wider refusal over the same rule.
  'not addressable',
] as const;

/**
 * Collapse whitespace before phrase-matching.
 *
 * NOT a nicety: this document carried "Keltner is not in / the catalog" across a line break, and a
 * per-line matcher read the file as clean while the false claim stood.
 */
function normalized(text: string): string {
  return text.replace(/\s+/g, ' ');
}

function sectionBody(markdown: string, heading: string): string {
  const start = markdown.indexOf(`\n${heading}\n`);
  if (start === -1) {
    throw new Error(`[skill-contract] no '${heading}' section to read the claim inventory from`);
  }
  const after = start + heading.length + 2;
  const next = markdown.indexOf('\n## ', after);
  return next === -1 ? markdown.slice(after) : markdown.slice(after, next);
}

/**
 * The identifiers of the first `{ … }` inline-code span in a section that is an IDENTIFIER LIST.
 *
 * The identifier test is load-bearing: the same document carries `{abs: "<tf>"}` in the header
 * grammar, `{"multiplier":1.5}` in the playbooks, and `{ signalId, timeframe }` as a tool-call
 * signature. Requiring unquoted comma-separated identifiers rejects a JSON blob rather than binding
 * an axis to one and passing.
 */
function braceListKeys(markdown: string, heading: string): string[] {
  const section = sectionBody(markdown, heading);
  for (const match of section.matchAll(/`\{([^`}]*)\}`/g)) {
    const keys = match[1]
      .split(',')
      .map((key) => key.trim())
      .filter((key) => key.length > 0);
    if (keys.length > 0 && keys.every((key) => /^[A-Za-z][A-Za-z0-9]*$/.test(key))) return keys;
  }
  throw new Error(
    `[skill-contract] '${heading}' carries no \`{ key, key, … }\` identifier list — the contract ` +
      `statement must stay readable as a brace-list of bare keys.`,
  );
}

function missingFrom(expected: readonly string[], actual: readonly string[]): string[] {
  const present = new Set(actual);
  return expected.filter((key) => !present.has(key));
}

describe('published skill states the live authoring contract', () => {
  it.each(Object.keys(AXIS_HEADING))('names every key the %s axis requires', (axis) => {
    expect(missingFrom(digest.axes[axis], braceListKeys(skill, AXIS_HEADING[axis]))).toEqual([]);
  });

  it.each(Object.keys(AXIS_HEADING))('names no key the %s axis rejects', (axis) => {
    expect(missingFrom(braceListKeys(skill, AXIS_HEADING[axis]), digest.axes[axis])).toEqual([]);
  });

  it('states the whole entry-trigger domain', () => {
    const entry = sectionBody(skill, AXIS_HEADING.entry);
    expect(digest.domains.entryTrigger.filter((member) => !entry.includes(member))).toEqual([]);
  });

  it('states the whole entry level-source domain', () => {
    const entry = sectionBody(skill, AXIS_HEADING.entry);
    expect(digest.domains.entryLevelSource.filter((member) => !entry.includes(member))).toEqual([]);
  });

  it('states the whole clock domain', () => {
    const conditions = sectionBody(skill, AXIS_HEADING.condition);
    expect(digest.domains.conditionClock.filter((member) => !conditions.includes(member))).toEqual([]);
  });

  it('states the whole authored-verdict domain', () => {
    const conditions = sectionBody(skill, AXIS_HEADING.condition);
    expect(digest.domains.conditionVerdict.filter((member) => !conditions.includes(member))).toEqual([]);
  });

  it('states the closes ceiling its constant carries', () => {
    // `closes` is meaningless without its ceiling, and the ceiling is a number rendered in prose
    // rather than a set — so the check is the rendered range, built from the constant.
    expect(sectionBody(skill, AXIS_HEADING.condition)).toContain(
      `1–${digest.bounds.conditionMaxCloses}`,
    );
  });
});

describe('published skill states no unverifiable vocabulary absence', () => {
  const claimed = [...sectionBody(skill, ABSENCE_HEADING).matchAll(/`([A-Z][A-Z0-9_]*)`/g)].map(
    (match) => match[1],
  );

  it('names only metric keys the catalog genuinely lacks', () => {
    // The detector for the drift that raises no error: contract 46.1 shipped all seven rows of the
    // table this section replaced, and nothing could notice — no request is made, no error is
    // raised, and the only effect is a paying author told a strategy cannot be built.
    const served = new Set(digest.metricKeys);
    expect(claimed.filter((key) => served.has(key))).toEqual([]);
  });

  it('names at least one key, so the section is checkable at all', () => {
    expect(claimed.length).toBeGreaterThan(0);
  });

  it.each(ABSENCE_PHRASES)('carries no unnameable "%s" claim outside that section', (phrase) => {
    const declared = normalized(sectionBody(skill, ABSENCE_HEADING));
    const outside = normalized(skill).split(declared);
    expect(outside.filter((part) => part.includes(phrase))).toEqual([]);
  });
});

describe('the contract check fails on the drift it was written for', () => {
  // A gate never seen to reject anything is not evidence that it works.
  it('reports the keys the pre-contract-44 recipe omitted', () => {
    const stale = '\n## X\n\n`{ conditionKey, name, definition, verdict, required }` — five.\n';
    expect(missingFrom(digest.axes.condition, braceListKeys(stale, '## X')).sort()).toEqual([
      'clock',
      'closes',
      'exit',
    ]);
  });

  it('reports a claimed-absent key the catalog now serves', () => {
    const served = new Set(digest.metricKeys);
    const rows = [...'| Keltner | `KC_UPPER` |'.matchAll(/`([A-Z][A-Z0-9_]*)`/g)].map((m) => m[1]);
    expect(rows.filter((key) => served.has(key))).toEqual(['KC_UPPER']);
  });

  it('sees a wrapped claim a line-based scan would miss', () => {
    const wrapped = 'Keltner is not in\n  the catalog, so substitute.';
    expect(wrapped.includes('not in the catalog')).toBe(false);
    expect(normalized(wrapped).includes('not in the catalog')).toBe(true);
  });

  it('refuses to bind an axis to a JSON example', () => {
    const jsonOnly = '\n## X\n\nTune it with `{"multiplier":1.5}`.\n';
    expect(() => braceListKeys(jsonOnly, '## X')).toThrow(/identifier list/);
  });

  it('fails loudly when the section itself is gone', () => {
    expect(() => sectionBody('# Something else\n\nNo conditions here.\n', '## Conditions')).toThrow(
      /no '## Conditions' section/,
    );
  });
});
